title: "Linatou DAO"
logo: img12.jpeg

description: "Portfolio personnel présentant mes projets, compétences et parcours en génie logiciel."

show_downloads: true
theme: jekyll-theme-minimal
lang: fr

projects:
  - title: Calculatrice
    description: Calculatrice réalisée en HTML, CSS et JavaScript.
    url: https://linatoudao7-art.github.io/CALCULATRICE/
