title: "Linatou DAO "
logo: img/nny.jpg
description:  "Portfolio personnel présentant mes projets, compétences et parcours en génie logiciel."
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
